// <auto-generated />
namespace TNBCSurvey.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Andrew3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Andrew3));
        
        string IMigrationMetadata.Id
        {
            get { return "202010301333558_Andrew-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
